package generator;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

import utilities.FileUtil;
import utilities.StringUtil;
import xml.parser.XmlParser;

@SuppressWarnings("serial")
public class ControlsMapGenerator extends EntityGenerator {

	Set<String> controlsInstanciators = new LinkedHashSet<String>();
	Set<String> instanciators = new LinkedHashSet<String>();
	Set<String> entitiesAssignments = new LinkedHashSet<String>();
	Set<String> tables = new LinkedHashSet<String>();
	Set<String> sceneControls = new LinkedHashSet<String>();
	Set<String> initializers = new LinkedHashSet<String>();
	List<String> fields = new ArrayList<String>();
	List<String> groupedControls = new ArrayList<String>();

	String queryMap = "";

	public void initializeControls() {
		controlsInstanciators = new LinkedHashSet<String>();
		instanciators = new LinkedHashSet<String>();
		entitiesAssignments = new LinkedHashSet<String>();
		tables = new LinkedHashSet<String>();
		sceneControls = new LinkedHashSet<String>();
		initializers = new LinkedHashSet<String>();
		fields = new ArrayList<String>();
		groupedControls = new ArrayList<String>();
	}

	public void generateSceneSwitch(File[] files) throws IOException {
		List<String> list = new ArrayList<String>();
		for (File file : files) {
			String fName = file.getName();
			if (fName.endsWith(".fxml")) {
				String className = fName.substring(0, fName.lastIndexOf("."));
				list.add(String.format("		_scenesMap.put(\"%s\", new %s(sceneSwitcher, client));", className, className));
			}
		}
		String template = "package sceneswitch;\r\n" + 
				"\r\n" + 
				"import java.util.HashMap;\r\n" + 
				"import java.util.Map;\r\n" + 
				"\r\n" + 
				"import javafx.stage.Stage;\r\n" + 
				"import sceneswitch.SceneBase.ISceneSwitcher;\r\n" + 
				"import wrapper.*;\r\n" + 
				"import client.IClient;\r\n" + 
				"\r\n" +
				"public class ScenesSwitch {\r\n" + 
				"\r\n" + 
				"	private Map<String, SceneBase> _scenesMap = new HashMap<String, SceneBase>();\r\n" + 
				"	\r\n" + 
				"	public ScenesSwitch(Stage stage, IClient client) throws Exception {\r\n" + 
				"		ISceneSwitcher sceneSwitcher = (scenesName) -> { stage.setScene(_scenesMap.get(scenesName).getScene()); };\r\n" + 
				"		\r\n" + 
				String.join("\r\n", list) +
				"	}\r\n" + 
				"\r\n" + 
				"	public SceneBase getScene(String key) {\r\n" + 
				"		return _scenesMap.get(key);\r\n" + 
				"	}\r\n" + 
				"}\r\n";
		File fileToWrite = new File("C:\\Java\\myFuelWorkspace\\MyFuelClient\\src\\sceneswitch\\ScenesSwitch.java");
		FileUtil.writeToFile(fileToWrite, template);
	}

	public void generateControlsWrappers(File directoryTo) throws Exception {
		Set<String> imports = new HashSet<String>();
		imports.add("import java.util.HashMap;");
		imports.add("import java.util.Map;");
		imports.add("import javafx.scene.Scene;");
		imports.add("import javafx.scene.image.ImageView;");
		imports.add("import controls.*;");
		imports.add("import sceneswitch.SceneBase;");
		imports.add("import javafx.fxml.FXMLLoader;");
		imports.add("import javafx.scene.Parent;");
		imports.add("import javafx.scene.control.*;");
		imports.add("import annotations.AutoGenerated;");
		imports.add("import action.*;");
		imports.add("import java.util.HashSet;");
		imports.add("import java.util.Set;");
		imports.add("import db.interfaces.IEntity;");
		imports.add("import javafx.scene.text.Text;");
		imports.add("import javafx.scene.layout.BorderPane;");
		imports.add("import widgets.table.Table;");
		imports.add("import table.MfTable;");
		imports.add("import widgets.table.*;");
		imports.add("import db.entity.*;");
		imports.add("import application.Main;");
		imports.add("import java.util.Collection;");
		imports.add("import client.IClient;\r\n");

		File outputDir = directoryTo;//"C:\\Java\\myFuelWorkspace\\MyFuelClient\\src\\wrapper");
		File[] files = new File("C:\\Java\\myFuelWorkspace\\MyFuelClient\\src\\application").listFiles();

		generateSceneSwitch(files);

		for (File file : files) {
			String fName = file.getName();
			if (fName.endsWith(".fxml")) {
				initializeControls();
				//"C:\\Java\\myFuelWorkspace\\MyFuelClient\\src\\application\\HomeHeatingTrack.fxml"
				prepareCollectionsFromFile(file.getAbsolutePath());

				if (groupedControls.size() > 0) {
					imports.add("import adapter.base.ControlAdapter;");
				}
				String className = fName.substring(0, fName.lastIndexOf("."));
				String template = StringUtil.replace(
						"package wrapper;\r\n" + 
								"\r\n" + 
								"<Imports>\r\n" + 
								"\r\n" + 
								"@AutoGenerated\r\n" + 
								"public class <ClassName> extends SceneBase {\r\n" + 
								"\r\n" + 
								"	public <ClassName>(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {\r\n" + 
								"		super(sceneSwitcher, client);\r\n" + 
								"		initialize();\r\n" + 
								"	}\r\n\n" + 
								"	public void initialize() throws Exception {\r\n" + 
								"		Parent root = FXMLLoader.load(Main.class.getResource(\"<FileName>\"));\r\n" + 
								"		_scene = new Scene(root);\r\n\n" +
								"<Lines>\r\n" + 
								"	}\r\n" +
								"<QueryMap>\r\n" + 
								"}", new HashMap<String, String>() {{
									put("<Imports>", String.join("\r\n", imports));
									put("<ClassName>", className);
									put("<FileName>", fName);
									put("<Lines>", getLines());
									put("<QueryMap>", queryMap);
								}});

				File fileToWrite = new File(String.format("%s\\%s.java", outputDir, className));
				FileUtil.writeToFile(fileToWrite, template);
			}
		}

		System.out.println("");
	}

	private String getLines() {
		return StringUtil.replace(
				"<SceneControls>" + 
						"<EntitiesInstanciation>" +
						"<EntitiesAssignments>" + 
						"<ControlsInstanciation>" +
						"<Tables>" + 
						"<EntitiesInitializers>" +
						"<EntitiesFields>" +
						"<Groups>", new HashMap<String, String>() {{
							put("<EntitiesInstanciation>", 
									(instanciators.size() > 0) ? ("\t\t//entities instantiation\r\n" + 
											String.join("\r\n", instanciators) + "\r\n\n") : "");
							put("<ControlsInstanciation>",
									(controlsInstanciators.size() > 0) ? ("\t\t//controls instantiation\r\n" + 
											String.join("\r\n", controlsInstanciators) + "\r\n\n") : "");
							put("<EntitiesInitializers>",
									(initializers.size() > 0) ? ("\t\t//initializations\r\n" + 
											String.join("\r\n\n", initializers) + "\r\n\n") : "");
							put("<EntitiesFields>", 
									(fields.size() > 0) ? ("\t\t//fields initializations\r\n" + 
											String.join("\r\n\n", fields) + "\r\n\n") : "");
							put("<Groups>",
									(groupedControls.size() > 0) ? ("\t\t//grouping\r\n" + 
											String.join("\r\n", groupedControls) + "\r\n") : "");
							put("<SceneControls>", 
									(sceneControls.size() > 0) ? ("\t\t//scene switchers\r\n" + 
											String.join("\r\n\n", sceneControls) + "\r\n\n") : "");
							put("<Tables>", 
									(tables.size() > 0) ? ("\t\t//tables instantiation\r\n" + 
											String.join("\r\n\n", tables) + "\r\n\n") : "");
							put("<EntitiesAssignments>", 
									(entitiesAssignments.size() > 0) ? ("\t\t//entities assignments\r\n" + 
											String.join("\r\n", entitiesAssignments) + "\r\n\n") : "");
						}});
	}

	private void populateTableControl(String controlName, String fxId, Map<String, List<String>> grouped) {
		String[] fxIdParts = fxId.split("\\$\\$\\$");
		String nameType = "";
		if (fxIdParts.length > 1 && fxIdParts[1].contains("$")) {
			String[] ntParts = fxIdParts[1].split("\\$");
			fxIdParts[0] += "$" + ntParts[1];
		}
		if (fxIdParts.length > 1) {
			nameType = StringUtil.swithToUpperCase(fxIdParts[1], "\\$");
		}
		String nameTypeF = nameType;
		String fxIdF = fxId;

		String[] paramValuesParts = fxIdParts[0].split("\\$\\$");
		String[] entitiesParts = paramValuesParts[0].split("\\$");
		String lastObjectName = null;
		for (int i = 1; i < entitiesParts.length - 1; ++i) {
			String className = StringUtil.swithToUpperCase(entitiesParts[i], "_");
			String objectName = StringUtil.firstToLowerCase(className);
			instanciators.add(String.format("\t\t%s %s = new %s();", className, objectName, className));
			if (i > 1) {
				String lastClassName = StringUtil.firstToUpperCase(lastObjectName);
				try {
					if (lastClassName.equals("Payment") || className.equals("Payment")) {
						System.out.println();
					}
					Class.forName("db.entity." + lastClassName).getDeclaredField("_" + entitiesParts[i]);
					entitiesAssignments.add(String.format("\t\t%s.set%s(%s);", lastObjectName, className, objectName));
				} catch (NoSuchFieldException | SecurityException | ClassNotFoundException e) {
					entitiesAssignments.add(String.format("\t\t%s.set%s(%s);", objectName, lastClassName, lastObjectName));
				}
			}
			lastObjectName = objectName;
		}

		String field = entitiesParts[entitiesParts.length - 1];
		String fieldVarName = StringUtil.swithToUpperCase(field, "_");
		fieldVarName = StringUtil.firstToLowerCase(fieldVarName);

		String fvName = fieldVarName;
		String loName = lastObjectName;
		String value = paramValuesParts.length > 1 ? 
				StringUtil.firstToUpperCase(paramValuesParts[1]) : "";
				controlsInstanciators.add(
						StringUtil.replace(
								"\t\tMf<Control> <FieldVarName>Control<Value><NameType> = new Mf<Control>((<Control>) _scene.lookup(\"#<FxId>\"));",
								new HashMap<String, String>() {{
									put("<Control>", controlName);
									put("<Value>", value);
									put("<FieldVarName>", fvName);
									put("<FxId>", fxIdF);
									put("<NameType>", nameTypeF);
								}}));
				fields.add(
						StringUtil.replace(
								"\t\t<FieldVarName>Control<Value><NameType>.setField(<Entity>.getClass().getDeclaredField(\"_<FieldName>\"));\r\n" +
										"\t\t<FieldVarName>Control<Value><NameType>.setEntity(<Entity>);",
										new HashMap<String, String>() {{
											put("<FieldVarName>", fvName);
											put("<Value>", value);
											put("<FieldName>", field);
											put("<Entity>", loName);
											put("<NameType>", nameTypeF);
										}}));
				String groupKey = paramValuesParts[0];
				if (!grouped.containsKey(groupKey)) {
					grouped.put(groupKey, new ArrayList<String>());
				}
				grouped.get(groupKey).add(fieldVarName + "Control" + value + nameTypeF);
	}

	private void populateActionControl(String controlName, String fxId) {
		String[] fxIdParts = fxId.split("\\$\\$\\$");
		String nameType = "";
		if (fxIdParts.length > 1 && fxIdParts[1].contains("$")) {
			String[] ntParts = fxIdParts[1].split("\\$");
			fxIdParts[0] += "$" + ntParts[1];
		}
		if (fxIdParts.length > 1) {
			nameType = StringUtil.swithToUpperCase(fxIdParts[1], "$");
		}
		String nameTypeF = nameType;
		String fxIdF = fxId;

		String[] parts = fxIdParts[0].split("\\$");
		String action = parts[1];
		String table = parts[parts.length - 1];
		String className = StringUtil.swithToUpperCase(table, "_");
		String objectName = StringUtil.firstToLowerCase(className);

		for (int i = 2; i < parts.length; ++i) {
			String cName = StringUtil.swithToUpperCase(parts[i], "_");
			String oName = StringUtil.firstToLowerCase(cName);
			instanciators.add(String.format("\t\t%s %s = new %s();", cName, oName, cName));
		}

		String capabilityEntity = "";
		String responseContent = "\t\t\t\n";
		if ("insert".equals(action) || "remove".equals(action)) {
			capabilityEntity = "\t\t<ObjectName><UAction>Capability<NameType>.addEntity(" + objectName + ");\n";
		}
		else if ("collect".equals(action)) {
			action = "filter";
			capabilityEntity = "\t\t<ObjectName><UAction>Capability<NameType>.setQueryEntities(prepareQuery(<ObjectName>));\n";

			queryMap = StringUtil.replace(
					"	private Map<IEntity, Map<String, String>> prepareQuery(<ClassName> <ObjectName>) {\r\n" + 
							"		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();\r\n" + 
							"		\r\n" + 
							"		Map<String, String> queryMap = new HashMap<String, String>();\r\n" + 
							"		\r\n" + 
							"		map.put(<ObjectName>, queryMap);\r\n" + 
							"		return map;\r\n" + 
							"	}",
							new HashMap<String, String>() {{
								put("<ObjectName>", objectName);
								put("<ClassName>", className);
							}});
			responseContent = 
					"			Collection<IEntity> entities = response.getEntities();\r\n" + 
							"			for (IEntity ientity : entities) {\r\n" + 
							"				<ClassName> entity = (<ClassName>) ientity;\r\n" + 
							"			}\n";

			//entityUiTable = "\t\t\t<ObjectName>Table.getObservableList().clear();\n" + 
			//"\t\t\t<ObjectName>Table.getObservableList().addAll(response.getEntitiesAsSet());\n";
		}
		else if ("update".equals(action)) {
			capabilityEntity = 
					"\t\tSet<IEntity> <ObjectName><UAction>Entities = new HashSet<IEntity>();\n" + 
							"\t\t<ObjectName><UAction>Capability<NameType>.setEntities(<ObjectName><UAction>Entities);\n";
		}

		String actionF = action.toLowerCase().equals("plain") ? "" : action;
		initializers.add(
				StringUtil.replace(
						"\t\tMf<Control> <Action><ClassName>Control<NameType> = new Mf<Control>((<Control>) _scene.lookup(\"#<FxId>\"));\n" + 
								"\t\tActionControl <ObjectName><Action>Action<NameType> = new ActionControl();\n" + 
								"\t\t<ObjectName><Action>Action<NameType>.setControl(<Action><ClassName>Control<NameType>);\n" + 
								"\t\t<UAction>Capability <ObjectName><UAction>Capability<NameType> = new <UAction>Capability();\n" +
								capabilityEntity + 

								"\t\t<ObjectName><Action>Action<NameType>.addCapability(<ObjectName><UAction>Capability<NameType>);\n" + 
								"\t\t<ObjectName><Action>Action<NameType>.setClient(_client);\n" +
								"\t\t<ObjectName><Action>Action<NameType>.setCallback((response) -> {\n" + 
								responseContent +
								"\t\t});",
								new HashMap<String, String>() {{
									put("<ClassName>", className);
									put("<ObjectName>", objectName);
									put("<Control>", controlName);
									put("<Action>", actionF);
									put("<UAction>", StringUtil.firstToUpperCase(actionF));
									put("<FxId>", fxIdF);
									put("<NameType>", nameTypeF);
								}}));
	}

	private void populateUiTables(String controlName, String fxId) {
		String[] fxIdParts = fxId.split("\\$\\$\\$");
		String nameType = "";
		if (fxIdParts.length > 1 && fxIdParts[1].contains("$")) {
			String[] ntParts = fxIdParts[1].split("\\$");
			fxIdParts[0] += "$" + ntParts[1];
		}
		if (fxIdParts.length > 1) {
			nameType = StringUtil.swithToUpperCase(fxIdParts[1], "$");
		}
		String nameTypeF = nameType;
		String fxIdF = fxId;

		String[] parts = fxIdParts[0].split("\\$");
		String editable = parts[1];
		String type = parts[2];
		String table = parts[3];
		String className = StringUtil.swithToUpperCase(table, "_");
		String objectName = StringUtil.firstToLowerCase(className);

		instanciators.add(String.format("\t\t%s %s = new %s();", className, objectName, className));

		tables.add(
				StringUtil.replace(
						"\t\tBorderPane <FieldVarName>Bp = (BorderPane) _scene.lookup(\"#<FxId>\");\n" + 
								"\t\tTable<<ClassName>> <FieldVarName>TableWrapper<NameType> = new Table<<ClassName>>();\n" + 
								"\t\tMfTable<<ClassName>> <FieldVarName>Table<NameType> = new MfTable<<ClassName>>(<ClassName>.class);\n" + 
								"\t\t<FieldVarName>Table<NameType>.setEditable(<Editable>);\n" + 
								"\t\tMf<UType>Decorator<<ClassName>> <FieldVarName><UType>Decorator<NameType> = new Mf<UType>Decorator<<ClassName>>();\n" + 
								"\t\t<FieldVarName>TableWrapper<NameType>.addDecorator(<FieldVarName><UType>Decorator);\n" + 
								"\t\t<FieldVarName>TableWrapper<NameType>.setTable(<FieldVarName>Table);\n" + 
								"\t\t<FieldVarName>Bp.setCenter(<FieldVarName>Table<NameType>);",
								new HashMap<String, String>() {{
									put("<ClassName>", className);
									put("<FieldVarName>", objectName);
									put("<UType>", StringUtil.firstToUpperCase(type));
									put("<Editable>", "editable".equals(editable) ? "true" : "false");
									put("<FxId>", fxIdF);
									put("<NameType>", nameTypeF);
								}}));
	}

	private void populateSceneControls(String controlName, String fxId) {
		String[] fxIdParts = fxId.split("\\$\\$\\$");
		String nameType = "";
		if (fxIdParts.length > 1 && fxIdParts[1].contains("$")) {
			String[] ntParts = fxIdParts[1].split("\\$");
			fxIdParts[0] += "$" + ntParts[1];
		}
		if (fxIdParts.length > 1) {
			nameType = StringUtil.swithToUpperCase(fxIdParts[1], "$");
		}
		String nameTypeF = nameType;
		String fxIdF = fxId;

		String[] parts = fxId.split("\\$");
		String sceneName = parts[1];
		sceneControls.add(
				StringUtil.replace(
						"\t\tMf<Control> <LSceneName>Control<NameType> = new Mf<Control>((<Control>) _scene.lookup(\"#<FxId>\"));\n" + 
								"\t\t<LSceneName>Control<NameType>.addEvent((event) -> { _switcher.switchScene(\"<SceneName>\"); });",
								new HashMap<String, String>() {{
									put("<LSceneName>", StringUtil.firstToLowerCase(sceneName));
									put("<SceneName>", sceneName);
									put("<Control>", controlName);
									put("<FxId>", fxIdF);
									put("<NameType>", nameTypeF);
								}}));
	}

	private void prepareCollectionsFromFile(String file) {
		try {
			Map<String, List<String>> grouped = new HashMap<String, List<String>>();
			XmlParser.parse(file, 
					(node) -> {
						String controlName = node.getNodeName();
						NamedNodeMap attributes = node.getAttributes();
						Node fxIdNode = attributes.getNamedItem("fx:id");
						if (fxIdNode != null) {
							String fxId = fxIdNode.getNodeValue();
							if (fxId.startsWith("table$")) {
								populateTableControl(controlName, fxId, grouped);
							}
							else if (fxId.startsWith("action$")) {
								populateActionControl(controlName, fxId);
							}
							else if (fxId.startsWith("uitable$")) {
								populateUiTables(controlName, fxId);
							}
							else if (fxId.startsWith("scene$")) {
								populateSceneControls(controlName, fxId);
							}
							System.out.println();
						}
					});

			for (Entry<String, List<String>> entry : grouped.entrySet()) {
				if (entry.getValue().size() > 1) {
					groupedControls.add(String.format("\t\tgroupControls(new ControlAdapter[] { %s });", 
							String.join(", ", entry.getValue())));
				}
			}
			System.out.println();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
