package generator;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import utilities.StringUtil;

public class EntityVisitorGenerator extends EntityGenerator {

	public void generateVisitor(File directory, String[] tables) throws IOException {
		Set<String> imports = new HashSet<String>();
		List<String> accessers = new ArrayList<String>();

		String className = "Visitor";
		String classTitle = String.format("@AutoGenerated\npublic class %s {", className);
		imports.add("import annotations.AutoGenerated;");

		for (String table : tables) {
			String entity = StringUtil.swithToUpperCase(table, "_");

			imports.add(String.format("import db.entity.%s;", entity));

			accessers.add(String.format("\tpublic void visit(%s %s) { };", 
					entity, entity.toLowerCase()));
		}

		createTableFile(directory, classTitle, className, imports, null, null, accessers);
		System.out.println("");
	}
}
